#!/system/bin/sh
#
# APN hack
#
/system/bin/toolbox rm /data/RS*.log
ln -s "/data/data/com.android.providers.telephony/shared_prefs/preferred-apn1.xml" "/data/data/com.android.providers.telephony/shared_prefs/preferred-apn.xml"
